### ISSUE TITLE
Bulk redo()

### ISSUE THREAD

**Issue by subramario** [ApplyBoard/coop-fall-2020-challenge#106]
Hey there,

If the number specified for bulk redo exceeds the number of undos performed, what should the expected output be?

Kind Regards,
Adi

**Comment by Vishesh-Gupta** [comment]
If the number of bulk_redo exceed than the undos performed then it should max the redo possible and then return that output as the final output.

**Comment by omasabdullah** [comment]
Hey @subramario if the amount of redos exceeds the amount possible, only redo what is possible and ignore the rest. @Vishesh-Gupta is correct :)

**Comment by subramario** [comment]
Sweet, thanks for the clarification fellas :) appreciate it!
