### ISSUE TITLE
Incorrect assertion in unit tests

### ISSUE THREAD

**Issue by rpecka** [ApplyBoard/coop-fall-2020-challenge#12]
In the python tests we have:
```
def test_redo():
    sourcer = EventSourcer()

    sourcer.add(5)
    sourcer.add(5)
    sourcer.add(5)
    sourcer.undo()
    sourcer.undo()
    sourcer.add(1)
    sourcer.redo()

    assert sourcer.value == 11
```
Seems like the order goes 0 -> 5 -> 10 -> 15 -> 10 -> 5 -> 6 -> nothing to redo since we added 1 which removed the future. Am I understanding the problem incorrectly?

**Comment by wesleymartin-ab** [comment]
That is correct yes! The add would invalidate the attempted redo.

**Comment by zeneiny** [comment]
Yeah, I'm of the same opinion, the redo stack should be empty after the add(1) as no undos have happened since the last edit.

**Comment by rpecka** [comment]
Just to be clear, I'm saying that I think the assertion should be `assert sourcer.value == 6`

**Comment by wesleymartin-ab** [comment]
@rpecka yes that is correct

**Comment by omasabdullah** [comment]
@rpecka although you overwrote the first undo, there is still another that exists. Check out the youtube video in the readme it does a great job explaining what we are looking for :)

**Comment by rpecka** [comment]
@omasabdullah In the video he says that if you undo and then make a change, you "break the future" and has a graphic showing that any changes made after an undo destroy any saved future states.

**Comment by omasabdullah** [comment]
For clarification, the answer should be 11 for anyone else curious. Rpecka jumped on the zoom call for clarification
