### ISSUE TITLE
Incorrect test case? - JS

### ISSUE THREAD

**Issue by daniel-weisdorf** [ApplyBoard/coop-fall-2020-challenge#15]
Two things - There seems to be an extra `test redo` that is just a duplicate of 'test undo'
```
test('test redo', () => {
  let sourcer = new EventSourcer();

  sourcer.add(2);
  sourcer.add(2);
  sourcer.add(2);
  sourcer.add(2);
  sourcer.undo();

  expect(sourcer.value).toEqual(6);
});
```

And the actual issue is the real `test redo` which has an incorrect output value as far as I can tell
```
test('test redo', () => {
  let sourcer = new EventSourcer();

  sourcer.add(5);
  sourcer.add(5);
  sourcer.add(5);
  sourcer.undo();
  sourcer.undo();
  sourcer.add(1);
  sourcer.redo();

  expect(sourcer.value).toEqual(11);
});
```

You add to 15, undo to 5, then add 1 to get to 6. The expected output seems to redo the undone 5, but the addition of 1 should be clearing the redo list, making the final output 6.

**Comment by masonc08** [comment]
I am also having this problem in the pytest module

**Comment by daniel-weisdorf** [comment]
Tacking on that `test bulk redo overstep` seems to also have the wrong output value.
```
test("test bulk redo overstep", () => {
  let sourcer = new EventSourcer();

  sourcer.add(5);
  sourcer.add(5);
  sourcer.add(5);
  sourcer.add(5);
  sourcer.add(5);
  sourcer.undo();
  sourcer.undo();
  sourcer.undo();
  sourcer.bulk_redo(5);

  expect(sourcer.value).toEqual(5);
});
```
Add to 25
Undo to 10
Redo 3 undoes to 25, 2 extra undoes go to the void.
Output should be 25 not 5?

**Comment by omasabdullah** [comment]
Hey @daniel-weisdorf @masonc08 check out the youtube video on the readme that explains the way we are looking for redo functionality.

If you look at the actions they will look like this where * denotes where we are looking in history, and thus the value should be the sum of all values before it.
5*
5, 5*,
5, 5, 5*
5, 5*, 5
5*, 5, 5
5, 1*, 5 
5, 1, 5*

**Comment by shivasurya** [comment]
@omasabdullah then why does the python and js has different test assertion values - https://github.com/ApplyBoard/coop-fall-2020-challenge/blob/master/tests/test_python_solution.py#L114

**Comment by omasabdullah** [comment]
@shivasurya will take a look at that right now thanks for bringing it up!

**Comment by omasabdullah** [comment]
@shivasurya yes that is an error on our side apologies, please update the test case accordingly

**Comment by shivasurya** [comment]
Sure. Thank you.

**Comment by GregFrench** [comment]
So just to clarify, the test case on line 131 in the JavaScript file should be 25, correct?

**Comment by daniel-weisdorf** [comment]
Just to be clear, you're looking for his description of a linkedlist process, but rather than clearing the future, actions are replaced and can be continued past.

**Comment by omasabdullah** [comment]
@GregFrench yes thats correct

**Comment by omasabdullah** [comment]
> Just to be clear, you're looking for his description of a linkedlist process, but rather than clearing the future, actions are replaced and can be continued past.

Yes thats correct
