### ISSUE TITLE
Clarification Regarding Redoing a Bulk Undo

### ISSUE THREAD

**Issue by masonc08** [ApplyBoard/coop-fall-2020-challenge#72]
Hi, assuming we do 
bulk_undo(6)
then we do
redo()
does this redo all of the 6 undos we just did, or does it only undo the last 1 out of the 6?

Maybe this was already asked. Sorry if it was.

Thanks in advance

**Comment by omasabdullah** [comment]
@masonc08 `redo()` will only redo one event not everything :)

**Comment by masonc08** [comment]
Thanks
